name: lighthouse

on:
  check_run:
    types:
      - completed
  workflow_dispatch:
  # Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g @lhci/cli@0.8.x
      - run: lhci autorun --collect.url=https://gatsby-test-nuk.pages.dev/